---

- hosts: my_env

  vars:
    autoconf: "{{ playbook_dir | dirname }}"
    user: "{{ lookup('env', 'USER') }}"
    desktop: "{{ lookup('env', 'DESKTOP_SESSION') }}"

  tasks:

  - name: Link .bashrc
    shell: "ln -sf {{ autoconf }}/linux/.bashrc ~"
  - name: Link .dircolors
    shell: "ln -sf {{ autoconf }}/linux/.dircolors ~"
  - name: Link .tmux.conf
    shell: "ln -sf {{ autoconf }}/linux/.tmux.conf ~"
  - name: Link .vimrc
    shell: "ln -sf {{ autoconf }}/vim/.vimrc ~"
  - name: Link .vim
    shell: "ln -sf {{ autoconf }}/vim/.vim ~"

  - name: Ensure docker group exists
    group:
      name: docker
      state: present
    become: true
  - name: Ensure current user in docker group
    user:
      name: "{{ user }}"
      groups:
        docker
      append: true
    become: true

  - name: Configure QTerminal
    block:
      - name: Ensure QTerminal colors dir exists
        stat:
          path: /usr/share/qtermwidget5/color-schemes/
        register: qtermcolors
      - name: Copy my QTerminal colorscheme
        copy:
          src: "{{ autoconf }}/linux/lxqt/QTerminal.colorscheme"
          dest: "{{ qtermcolors.stat.path }}"
        when: qtermcolors.stat.exists
        become: true
      - name: Configure QTerminal colors
        ini_file:
          path: ~/.config/qterminal.org/qterminal.ini
          section: General
          option: "{{ item.key }}"
          value: "{{ item.val }}"
        loop:
          - {key: "Term", val: "xterm-256color"}
          - {key: "colorScheme", val: "QTerminal"}
        when: qtermcolors.stat.exists

  - name: Configure LXQT desktop
    vars:
      vim_desktop: in-vim.desktop
    block:
      - name: Add open in Vim context to file manager
        file:
          src: "{{ autoconf }}/linux/lxqt/{{ vim_desktop }}"
          dest: "~/.local/share/applications/{{ vim_desktop }}"
          state: link
      - name: Set default file associations for Vim
        ini_file:
          path: ~/.config/mimeapps.list
          section: Default Applications
          option: "{{ item }}"
          value: "{{ vim_desktop }};"
        loop:
          - text/plain
          - text/markdown
          - text/css
          - text/x-scss
          - text/x-python
          - text/x-python3
          - text/x-makefile
          - application/javascript
          - application/json
          - application/x-yaml
      - name: Update desktop database
        shell: update-desktop-database
        become: true
    when: desktop is match(".*/lxqt")

