---

- hosts: my_env

  vars:
    conf_dir: "{{ playbook_dir | dirname }}"
    user: "{{ lookup('env', 'USER') }}"

  tasks:

  - name: Link .bashrc
    shell: "ln -sf {{ conf_dir }}/linux/.bashrc ~"
  - name: Link .dircolors
    shell: "ln -sf {{ conf_dir }}/linux/.dircolors ~"
  - name: Link .tmux.conf
    shell: "ln -sf {{ conf_dir }}/linux/.tmux.conf ~"
  - name: Link .vimrc
    shell: "ln -sf {{ conf_dir }}/vim/.vimrc ~"
  - name: Link .vim
    shell: "ln -sf {{ conf_dir }}/vim/.vim ~"

  - name: Ensure docker group exists
    group:
      name: docker
      state: present
    become: true
  - name: Ensure current user in docker group
    user:
      name: "{{ user }}"
      groups:
        docker
      append: true
    become: true

  - name: Ensure QTerminal colors dir exists
    stat:
      path: /usr/share/qtermwidget5/color-schemes/
    register: qtermcolors
  - name: Copy my QTerminal colorscheme
    copy:
      src: "{{ conf_dir }}/linux/lxqt/QTerminal.colorscheme"
      dest: "{{ qtermcolors.stat.path }}"
    when: qtermcolors.stat.exists
    become: true
  - name: Set 256-colored terminal
    ini_file:
      path: ~/.config/qterminal.org/qterminal.ini
      section: General
      option: Term
      value: xterm-256color
    when: qtermcolors.stat.exists
  - name: Set my colorscheme in QTerminal settings
    ini_file:
      path: ~/.config/qterminal.org/qterminal.ini
      section: General
      option: colorScheme
      value: QTerminal
    when: qtermcolors.stat.exists

